# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PowerShell@2
  displayName: 'PowerShell Script'
  inputs:
    targetType: filePath
    filePath: ./ApplyVersion.ps1
- task: CopyFiles@2
  inputs:
    contents: |
      !(*.ps1)
    targetFolder:
      Distributed_Chests
    cleanTargetFolder: true
    overWrite: true
    preserveTimestamp: true
- task: CopyFiles@2
  inputs:
    contents: |
      (changelog.txt)
    targetFolder:
      $(Build.ArtifactStagingDirectory)/changelog.txt
    overWrite: true
    preserveTimestamp: true
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'Distributed-Chests' 
    includeRootFolder: true 
    archiveType: 'zip'    
    archiveFile: '$(Build.ArtifactStagingDirectory)/Distributed-Chests_$(Env:BUILD_BUILDNUMBER).zip' 
    replaceExistingArchive: true 
- task: GitHubRelease@0
  inputs:
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'auto'
    title: 'Distributed'
    releaseNotesFile: '$(Build.ArtifactStagingDirectory)/changelog.txt'
    assets: '$(Build.ArtifactStagingDirectory)/Distributed-Chests_$(Env:BUILD_BUILDNUMBER).zip'
    isPreRelease: true
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'