# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'Hosted VS2017'

variables:
  Version.MajorMinor: 0.1
  Version.Patch: $[counter(variables['Version.MajorMinor'], 0)]

name: $(Version.MajorMinor).$(Version.Patch)

steps:
- task: PowerShell@2
  displayName: 'PowerShell Script'
  inputs:
    targetType: filePath
    filePath: ./ApplyVersionNumber.ps1
    
- task: CopyFiles@2
  inputs:
    Contents: |
      !(*.ps1)
      !(*.yml)
    TargetFolder: '$(Build.ArtifactStagingDirectory)/Distributed_Chests'
    preserveTimestamp: true
    includeRootFolder: true 
    archiveType: 'zip'    
    archiveFile: '$(Build.ArtifactStagingDirectory)/Distributed-Chests_$(Env:BUILD_BUILDNUMBER).zip' 
    replaceExistingArchive: true 
- task: CopyFiles@2
  inputs:
    contents: changelog.txt
    targetFolder:
      $(Build.ArtifactStagingDirectory)/changelog.txt
    overWrite: true
    preserveTimestamp: true
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/Distributed-Chests' 

- task: GitHubRelease@0
  inputs:
    gitHubConnection: github.com
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'auto'
    title: 'Distributed'
    releaseNotesFile: '$(Build.ArtifactStagingDirectory)/changelog.txt'
    assets: '$(Build.ArtifactStagingDirectory)/Distributed-Chests_$(Env:BUILD_BUILDNUMBER).zip'
    isPreRelease: true
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'